config/routes.rb
require 'api_constraints'

YourNextRoom::Application.routes.draw do
  devise_for :admins, controllers: { sessions: "admin/sessions" }
	namespace :admin do
		root 'home#index'
		resources :tenants
		resources :landlords
		resources :managers
		resources :users
    resources :admin_users
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :api do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete

        match '/confirmations' => 'confirmations#create', :via => :post
        match '/confirmations' => 'confirmations#show', :via => :get

        match '/passwords' => 'passwords#create', :via => :post
        match '/passwords' => 'passwords#update', :via => :put

        match '/update_password' => 'passwords#update_password', :via => :put

      end
      resources :users, only: [:create]
      match '/users' => 'users#show', :via => :get
      match '/users' => 'users#update', :via => :put
      match '/users' => 'users#destroy', :via => :delete

      resources :tenants
      match '/tenants' => 'tenants#update', :via => :put
      match '/tenants' => 'tenants#destroy', :via => :delete

      resources :landlords
      match '/landlords' => 'landlords#update', :via => :put
      match '/landlords' => 'landlords#destroy', :via => :delete

      resources :managers
      match '/managers' => 'managers#update', :via => :put
      match '/managers' => 'managers#destroy', :via => :delete
    end
  end
end

app/models/manager.rb
require 'open-uri'

class Manager < ActiveRecord::Base
  has_one :user, as: :role, dependent: :nullify

  accepts_nested_attributes_for :user

  attr_accessor :contact_person_image_url

  has_attached_file :contact_person_photo,
    :path => ":rails_root/public/resources/contact/:id/:filename",
    :url  => "/resources/contact/:id/:filename"

  validates_presence_of :company_name
  validates_presence_of :phone_number
  #validates_presence_of :street
  #validates_presence_of :city
  #validates_presence_of :postal_code
  #validates_presence_of :state
  #validates_presence_of :country
  #validates_presence_of :occupation
  #validates_presence_of :page_url
  validates_presence_of :estate_agent
  validates_presence_of :verify_properties
  validates_presence_of :contact_person_full_name
  validates_presence_of :contact_person_email_address
  #validates_presence_of :contact_person_occupation
  validates_presence_of :contact_person_phone_number
  validates_presence_of :contact_person_position

  do_not_validate_attachment_file_type :contact_person_photo

  def contact_person_image_url=(image_url)
    return unless image_url.present?
    self.contact_person_photo = URI.parse(image_url)
  end
end

app/controllers/admin/managers_controller.rb
class Admin::ManagersController < Admin::AdminController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  def index
    @managers = Manager.all.paginate(:page => params[:page], :per_page => 10)
  end

  def show
  end

  def new
    @manager = Manager.new
    @user = @manager.build_user
  end

  def edit
  end

  def create
    @manager = Manager.new(manager_params)
    respond_to do |format|
      if @manager.save
        user = User.find_by_role_id(@manager.id)
        @manager.user_id = user.id
        @manager.save
        format.html { redirect_to admin_managers_url, notice: 'Manager was successfully created.' }
        format.json { render action: 'show', status: :created, location: @manager }
      else
        format.html { render action: 'new' }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to admin_managers_url, notice: 'Manager was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(@manager.user_id)
    @user.destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to admin_managers_url }
      format.json { head :no_content }
    end
  end

  def home
  end  

  private
    def set_manager
      @manager = Manager.find(params[:id])
    end

    def manager_params
      params.require(:manager).permit(:company_name, :company_description, :phone_number, :verify_properties, :estate_agent,
                                      :contact_person_full_name, :contact_person_email_address,:contact_person_position, :contact_person_photo, :contact_person_image_url,
                                      :street, :city, :postal_code, :state, :country, :occupation, :page_url, :contact_person_phone_number, :contact_person_occupation,
                                      :user_attributes => [:id, :email, :username, :password, :password_confirmation, :avatar, :avatar_image_url, :account_type])
    end
end

app/controllers/api/v1/managers_controller.rb
class Api::V1::ManagersController < Api::V1::BaseController

  before_filter :authenticate_user!, :except => [:index, :show]
  respond_to :html, :json

  def index
    respond_with :api, Manager.all
  end

  def show
    manager = Manager.find(params[:id])
    respond_with :api, manager.to_json({:include => [:user]})
  end

  def create
    if current_user.role_id == nil
      @manager = Manager.new(manager_params)
      @manager.user = current_user
      @manager.user_id = current_user.id
      if @manager.save
        render :json => @manager, :status => 200
      else
        render :json => {:errors => @manager.errors}, :status => 401
      end
    else
      render :json => {:error => 'User already has a profile'}, :status => 401
    end
  end

  def update
    if current_user.role_type == 'Manager'
      @manager = Manager.update(current_user.role_id, manager_params)
      render :json => @manager, :status => 200
    else
      render :json => {:error => 'User is not a manager'}, :status => 401
    end
  end

  def destroy
    if current_user.role_type == 'Manager'
      @manager = Manager.find(current_user.role_id)
      @manager.user.role = nil
      @manager.user.save
      respond_with :api, @manager.destroy
    else
      render :json => {:error => 'User is not a manager'}, :status => 401
    end
  end

  private
    def manager_params
      params.require(:manager).permit(:company_name, :company_description, :phone_number, :verify_properties, :estate_agent, :contact_person_full_name, :contact_person_email_address, :contact_person_position, :contact_person_image_url)
    end

end

app/helpers/admin/managers_helper.rb
module Admin::ManagersHelper
end

app/helpers/api/managers_helper.rb
module Api::ManagersHelper
end

app/views/admin/managers/_fetchAllManager.html.haml
%section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-body
          %table.table.table-bordered
            %tr              
              %th Company Name
              %th Company Phone Number
              %th Contact Person Name
              %th Contact Person Phone Number
              %th Contact Person Email
              %th Contact Person Position

              %th Actions
            %tr
            - if @managers.size > 0
              - @managers.each do |manager|
                %tr
                  %td= manager.company_name
                  %td= manager.phone_number
                  %td= manager.contact_person_full_name
                  %td= manager.contact_person_phone_number
                  %td= manager.contact_person_email_address
                  %td= manager.contact_person_position
                  %td
                    = link_to 'Edit', edit_admin_manager_path(manager) 
                    |
                    = link_to 'Show', admin_manager_path(manager)
                    |
                    = link_to 'Delete', admin_manager_path(manager) , :method=>:delete, :data => {:confirm=>"Are you sure?" }
            - else
              %div No record found.
        .box-footer.clearfix
          %ul.pagination.pagination-sm.no-margin.pull-right
            %li
              = will_paginate @managers, :previous_label => '&laquo;', :next_label => '&raquo;'
            %br/
          = link_to 'Add New', new_admin_manager_path, :class => 'btn btn-primary'
        / /.box-body
      / /.box
    / /.col
  / /.row
/ /.content
/ /.content-wrapper

app/views/admin/managers/_form.html.haml
%section.content
  .row
    .col-md-12
      .box.box-primary
        = form_for ["admin", @manager] do |f|
          = f.fields_for :user do |builder|
            .box-body
              %br
              .field
                %label User Name
                = builder.text_field :username, :class => 'form-control'
                - if @manager.user.errors[:username].any?
                  %span.myerror
                    = @manager.user.errors[:username].first
              %br
              .field
                %label Account Type
                %br
                = builder.select :account_type, options_for_select([["Select Account Type", ""], "Basic", "Premium"]), {}, :class => 'form-control'
                - if @manager.user.errors[:account_type].any?
                  %span.myerror
                    = @manager.user.errors[:account_type].first
              %br
              .field
                = builder.file_field :avatar, :id => "filePhoto"
                %img{:alt => "", :id => "imgPreview"} 
              %br
              .field
                %label Email
                %br
                = builder.text_field :email, :class => 'form-control'
                - if @manager.user.errors[:email].any?
                  %span.myerror
                    = @manager.user.errors[:email].first
              %br
              .field
                %label Password
                %br
                = builder.password_field :password, :class => 'form-control'
                - if @manager.user.errors[:password].any?
                  %span.myerror
                    = @manager.user.errors[:password].first
              %br
              .field
                %label Password Confirmation
                %br
                = builder.password_field :password_confirmation, :class => 'form-control'
                - if @manager.user.errors[:password_confirmation].any?
                  %span.myerror
                    = @manager.user.errors[:password_confirmation].first
              %br
              .field
                %label Company Name     
                %br  
                = f.text_field :company_name, :class => 'form-control'
                - if @manager.errors[:company_name].any?
                  %span.myerror
                    = @manager.errors[:company_name].first
              %br
              .field
                %label Phone Number     
                %br
                = f.text_field :phone_number, :class => 'form-control'
                - if @manager.errors[:phone_number].any?
                  %span.myerror
                    = @manager.errors[:phone_number].first
              %br
              .field
                %label Street     
                %br
                = f.text_field :street, :class => 'form-control'
                - if @manager.errors[:street].any?
                  %span.myerror
                    = @manager.errors[:street].first
              %br
              .field
                %label City   
                %br
                = f.text_field :city, :class => 'form-control'
                - if @manager.errors[:city].any?
                  %span.myerror
                    = @manager.errors[:city].first
              %br
              .field
                %label Postal Code     
                %br
                = f.text_field :postal_code, :class => 'form-control'
                - if @manager.errors[:postal_code].any?
                  %span.myerror
                    = @manager.errors[:postal_code].first
              %br
              .field
                %label State    
                %br
                = f.text_field :state, :class => 'form-control'
                - if @manager.errors[:state].any?
                  %span.myerror
                    = @manager.errors[:state].first
              %br
              .field
                %label Country     
                %br
                = f.text_field :country, :class => 'form-control'
                - if @manager.errors[:country].any?
                  %span.myerror
                    = @manager.errors[:country].first

              %br
              .field
                %label Company Description
                %br
                = f.text_area :company_description, :class => 'form-control'
              %br
              .field
                %label Page Url    
                %br
                = f.text_field :page_url, :class => 'form-control'
                / - if @manager.errors[:page_url].any?
                /   %span.myerror
                /     = @manager.errors[:page_url].first
              %br
              .field
                %label Add Page  
                %br
                = f.text_field :add_page, :class => 'form-control'
                / - if @manager.errors[:add_page].any?
                /   %span.myerror
                /     = @manager.errors[:add_page].first
              %br
              .checkbox
                %label
                  = f.check_box :verify_properties
                  Verify Properties
                - if @manager.errors[:verify_properties].any?
                  %br
                    %span.myerror
                      = @manager.errors[:verify_properties].first
              %br
              .checkbox
                %label
                  = f.check_box :estate_agent
                  Estate Agent
                - if @manager.errors[:estate_agent].any?
                  %br
                    %span.myerror
                      = @manager.errors[:estate_agent].first

              / %br
              / .checkbox
              /   %label
              /   = f.check_box :verify_properties
              /   Verify Properties
              /   - if @manager.errors[:verify_properties].any?
              /     %span
              /       = @manager.errors[:verify_properties].first
                    
              / %br
              / .checkbox
              /   %label
              /   = f.check_box :estate_agent
              /   Estate Agent
              /   - if @manager.errors[:estate_agent].any?
              /     %span
              /       = @manager.errors[:estate_agent].first
              %br
              .field
                %label Contact Person Full Name
                %br
                = f.text_field :contact_person_full_name, :class => 'form-control'
                - if @manager.errors[:contact_person_full_name].any?
                  %span.myerror
                    = @manager.errors[:contact_person_full_name].first
              %br
              .field
                %label Contact Person Email Address                
                %br
                = f.text_field :contact_person_email_address, :class => 'form-control'
                - if @manager.errors[:contact_person_email_address].any?
                  %span.myerror
                    = @manager.errors[:contact_person_email_address].first
              %br
              .field
                %label Contact Person Phone Number               
                %br
                = f.text_field :contact_person_phone_number, :class => 'form-control'
                - if @manager.errors[:contact_person_phone_number].any?
                  %span.myerror
                    = @manager.errors[:contact_person_phone_number].first
              %br
              .field
                %label Occupation
                %br
                = f.select :occupation, options_for_select([["Select occupation", ""], "Student", "Professional", "Other"]), {}, :class => 'form-control'
                - if @manager.errors[:occupation].any?
                  %span.myerror
                    = @manager.errors[:occupation].first
              %br
              .field
                %label Contact Person Position                
                %br
                = f.text_field :contact_person_position, :class => 'form-control'
                - if @manager.errors[:contact_person_position].any?
                  %span.myerror
                    = @manager.errors[:contact_person_position].first
              %br
              .field
                = f.file_field :contact_person_photo, :id => "contactImage"
                %img{:alt => "", :id => "personPhoto"} 
              %br
              .box-footer
                = f.submit 'Submit', :class => 'btn btn-primary' 
                = link_to 'Back', admin_managers_path, :class => 'btn btn-primary'
            / %br
            / .actions
            /   = f.submit 'Submit', :class => 'btn btn-primary' 
            /   = link_to 'Back', admin_managers_path, :class => 'btn btn-primary'
                
:javascript
  var imageLoader = document.getElementById('filePhoto');
      imageLoader.addEventListener('change', handleImage, false);
  function handleImage(e) {
      var reader = new FileReader();
      reader.onload = function (event) {
          $('#imgPreview').attr('src',event.target.result);
      }
      reader.readAsDataURL(e.target.files[0]);
  }

  var imageLoader = document.getElementById('contactImage');
      imageLoader.addEventListener('change', conImage, false);
  function conImage(e) {
      var myreader = new FileReader();
      myreader.onload = function (e) {
          $('#personPhoto').attr('src',e.target.result);
      }
      myreader.readAsDataURL(e.target.files[0]);
  }

app/views/admin/managers/edit.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      &nbsp;
      Edit Business Landlord
  = render 'form'

app/views/admin/managers/index.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      &nbsp;
      List of Business Landlords
  = render 'fetchAllManager'

app/views/admin/managers/new.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      &nbsp;
      Add New Business Landlord
  = render 'form'

app/views/admin/managers/show.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1 Business Landlord Details
    .row
      .col-md-12
        .box.box-primary
          .box-body
            %table.table.table-striped
              %p#notice= notice
              %p
                %strong Id:
                = @manager.id
              %p
                %strong Company Name:
                = @manager.company_name
              %p
                %strong Phone Number:
                = @manager.phone_number
              %p
                %strong Street:
                = @manager.street
              %p
                %strong City:
                = @manager.city
              %p
                %strong Postal Code:
                = @manager.postal_code
              %p
                %strong State:
                = @manager.state
              %p
                %strong Country:
                = @manager.country
              %p
                %strong Contact Person FullName:
                = @manager.contact_person_full_name
              %p
                %strong Contact Person Email:
                = @manager.contact_person_email_address
              %p
                %strong Contact Person Occupation:
                = @manager.contact_person_occupation
              %p
                %strong Contact Person Phone Number:
                = @manager.contact_person_phone_number
              %p
                %strong Contact Person Position:
                = @manager.contact_person_position
              %p
                %strong Occupation:
                = @manager.occupation
              - if @manager.contact_person_photo.present?
                %p
                  %strong Contact Person Photo:
                  = image_tag @manager.contact_person_photo, :size => "50x50"
              %p
                %strong User Id:
                = @manager.user_id
              %p
                %strong Account Type:
                = @manager.user.account_type
              %p
                %strong User Name:
                = @manager.user.username
              %p
                %strong Email:
                = @manager.user.email
              - if @manager.user.avatar.present?
                %p
                  %strong Photo:
                  = image_tag @manager.user.avatar, :size => "50x50"
              %p
              .box-footer
                = link_to 'Edit', edit_admin_manager_path(@manager), :class => 'btn btn-primary'
                &nbsp;
                = link_to 'Back', admin_managers_path, :class => 'btn btn-primary'