config/routes.rb
require 'api_constraints'

YourNextRoom::Application.routes.draw do
  devise_for :admins, controllers: { sessions: "admin/sessions" }
	namespace :admin do
		root 'home#index'
		resources :tenants
		resources :landlords
		resources :managers
		resources :users
    resources :admin_users
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :api do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete

        match '/confirmations' => 'confirmations#create', :via => :post
        match '/confirmations' => 'confirmations#show', :via => :get

        match '/passwords' => 'passwords#create', :via => :post
        match '/passwords' => 'passwords#update', :via => :put

        match '/update_password' => 'passwords#update_password', :via => :put

      end
      resources :users, only: [:create]
      match '/users' => 'users#show', :via => :get
      match '/users' => 'users#update', :via => :put
      match '/users' => 'users#destroy', :via => :delete

      resources :tenants
      match '/tenants' => 'tenants#update', :via => :put
      match '/tenants' => 'tenants#destroy', :via => :delete

      resources :landlords
      match '/landlords' => 'landlords#update', :via => :put
      match '/landlords' => 'landlords#destroy', :via => :delete

      resources :managers
      match '/managers' => 'managers#update', :via => :put
      match '/managers' => 'managers#destroy', :via => :delete
    end
  end
end

app/models/landlord.rb
require "open-uri"

class Landlord < ActiveRecord::Base
  has_one :user, as: :role, dependent: :nullify

  accepts_nested_attributes_for :user

  validates_presence_of :title
  validates_presence_of :full_name
  validates_presence_of :gender
  validates_presence_of :date_of_birth
  validates_presence_of :address_type
  validates_presence_of :address
  validates_presence_of :city
  validates_presence_of :postal_code
  validates_presence_of :country
  validates_presence_of :occupation
end

app/controllers/admin/landlords_controller.rb
class Admin::LandlordsController < Admin::AdminController
  before_action :set_landlord, only: [:show, :edit, :update, :destroy]

  def index
    @landlords = Landlord.all.paginate(:page => params[:page], :per_page => 10)
  end

  def show
  end

  def new
    @landlord = Landlord.new
    @user = @landlord.build_user
  end

  def edit
  end

  def create
    @landlord = Landlord.new(landlord_params)
    respond_to do |format|
      if @landlord.save
        user = User.find_by_role_id(@landlord.id)
        @landlord.user_id = user.id
        @landlord.save
        format.html { redirect_to admin_landlords_url, notice: 'Landlord was successfully created.' }
        format.json { render action: 'show', status: :created, location: @landlord }
      else
        format.html { render action: 'new' }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @landlord.update(landlord_params)
        format.html { redirect_to admin_landlords_url, notice: 'Landlord was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
      @user = User.find(@landlord.user_id)
      @user.destroy
      @landlord.destroy
      respond_to do |format|
        format.html { redirect_to admin_landlords_url }
        format.json { head :no_content }
      end
  end

  private
    def set_landlord
      @landlord = Landlord.find(params[:id])
    end

    def landlord_params
      params.require(:landlord).permit(:title, :full_name, :gender, :date_of_birth, :address_type, :address, :city, :postal_code, :country, :occupation, :brief_description, :user_attributes => [:id, :email, :username, :password, :password_confirmation, :avatar, :avatar_image_url, :account_type])
    end
end

app/controllers/api/v1/landlords_controller.rb
class Api::V1::LandlordsController < Api::V1::BaseController
  before_filter :authenticate_user!, :except => [:index, :show]
  respond_to :html, :json

  def index
    respond_with :api, Landlord.all
  end

  def show
    landlord = Landlord.find(params[:id])
    respond_with :api, landlord.to_json({:include => [:user]})
  end

  def create
    if current_user.role_id == nil
      @landlord = Landlord.new(landlord_params)
      @landlord.user = current_user
      @landlord.user_id = current_user.id
      if @landlord.save
        render :json => @landlord, :status => 200
      else
        render :json => {:errors => @landlord.errors}, :status => 401
      end
    else
      render :json => {:error => 'User already has a profile'}, :status => 401
    end
  end

  def update
    if current_user.role_type == 'Landlord'
      respond_with :api, Landlord.update(current_user.role_id, landlord_params)
    else
      render :json => {:error => 'User is not a landlord'}, :status => 401
    end
  end

  def destroy
    if current_user.role_type == 'Landlord'
      @landlord = Landlord.find(current_user.role_id)
      @landlord.user.role = nil
      @landlord.user.save
      respond_with :api, @landlord.destroy
    else
      render :json => {:error => 'User is not a landlord'}, :status => 401
    end
  end

  private
    def landlord_params
      params.require(:landlord).permit(:title, :full_name, :gender, :date_of_birth, :address_type, :address, :city, :postal_code, :country, :occupation, :brief_description, :verify_properties)
    end

end

app/helpers/admin/landlords_helper.rb
module Admin::LandlordsHelper
end

app/helpers/api/landlords_helper.rb
module Api::LandlordsHelper
end

app/views/admin/landlords/_fetchAllLandlord.html.haml
%section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-body
          %table.table.table-bordered
            %tr
              %th Title
              %th Full Name
              %th Gender
              %th Date of Birth
              %th Address Type
              %th Address
              %th City
              %th Postal Code
              %th Country
              %th Occupation
              %th Actions
            %tr
            - if @landlords.size > 0
              - @landlords.each do |landlord|
                %tr
                  %td= landlord.title
                  %td= landlord.full_name
                  %td= landlord.gender
                  %td= landlord.date_of_birth
                  %td= landlord.address_type
                  %td= landlord.address
                  %td= landlord.city
                  %td= landlord.postal_code
                  %td= landlord.country
                  %td= landlord.occupation
                  %td
                    = link_to 'Edit', edit_admin_landlord_path(landlord)
                    |
                    = link_to 'Show', admin_landlord_path(landlord)
                    |
                    = link_to 'Delete', admin_landlord_path(landlord) , :method=>:delete, :data => {:confirm=>"Are you sure?" }
            - else
              %div No record found.
        .box-footer.clearfix
          %ul.pagination.pagination-sm.no-margin.pull-right
            %li
            = will_paginate @landlord, :previous_label => '&laquo;', :next_label => '&raquo;'
            %br/
          = link_to 'Add New', new_admin_landlord_path, :class => 'btn btn-primary'
        / /.box-body
      / /.box
    / /.col
  / /.row
/ /.content
/ /.content-wrapper

app/views/admin/landlords/_form.html.haml
%section.content
  .row
    .col-md-12
      .box.box-primary
        = form_for ["admin", @landlord] do |f|
          = f.fields_for :user do |builder|
            .box-body
              %br
              .field
                %label User Name
                = builder.text_field :username, :class => 'form-control'
                - if @landlord.user.errors[:username].any?
                  %span.myerror
                    = @landlord.user.errors[:username].first
              %br
              .field
                %label Account Type
                %br
                = builder.select :account_type, options_for_select([["Select Account Type", ""], "Basic", "Premium"]), {}, :class => 'form-control'
                - if @landlord.user.errors[:account_type].any?
                  %span.myerror
                    = @landlord.user.errors[:account_type].first
              %br
              .field
                = builder.file_field :avatar, :id => "filePhoto"
                %img{:alt => "", :id => "imgPreview"}            
              %br
              .field
                %label Email
                %br
                = builder.text_field :email, :class => 'form-control'
                - if @landlord.user.errors[:email].any?
                  %span.myerror
                    = @landlord.user.errors[:email].first

              %br
              .field
                %label Password
                %br
                = builder.password_field :password, :class => 'form-control'
                - if @landlord.user.errors[:password].any?
                  %span.myerror
                    = @landlord.user.errors[:password].first
              %br
              .field
                %label Password Confirmation
                %br
                = builder.password_field :password_confirmation, :class => 'form-control'
                - if @landlord.user.errors[:password_confirmation].any?
                  %span.myerror
                    = @landlord.user.errors[:password_confirmation].first
              %br
              .field
                %label Title
                %br
                = f.select :title, options_for_select([["Select Title", ""], "Mr", "Mrs", "Ms", "Miss", "Sir", "Madam"]), {}, :class => 'form-control'
                - if @landlord.errors[:title].any? 
                  %span.myerror
                    = @landlord.errors[:title].first
              %br
              .field
                %label Full Name
                = f.text_field :full_name, :class => 'form-control'
                - if @landlord.errors[:full_name].any?
                  %span.myerror
                    = @landlord.errors[:full_name].first
                %br
                .field
                  %label Gender
                  %br
                  = f.select :gender, options_for_select([["Select Gender", ""], "Male", "Female"]), {}, :class => 'form-control'
                  - if @landlord.errors[:gender].any?
                    %span.myerror
                      = @landlord.errors[:gender].first
                %br
                .field
                  %label Date of Birth
                  = f.text_field :date_of_birth, :class => 'form-control'
                  - if @landlord.errors[:date_of_birth].any?
                    %span.myerror
                      = @landlord.errors[:date_of_birth].first
                %br
                .field
                  %label Address Type
                  %br
                  = f.select :address_type, options_for_select(["Home", "Work"]), {}, :class => 'form-control'
                  - if @landlord.errors[:address_type].any?
                    %span.myerror
                      = @landlord.errors[:address_type].first
                %br
                .field
                  %label Address
                  = f.text_area :address, :class => 'form-control'
                  - if @landlord.errors[:address].any?
                    %span.myerror
                      = @landlord.errors[:address].first
                %br
                .field
                  %label City      
                  = f.text_field :city, :class => 'form-control'
                  - if @landlord.errors[:city].any?
                    %span.myerror
                      = @landlord.errors[:city].first
                %br
                .field
                  %label Postal Code
                  = f.text_field :postal_code, :class => 'form-control'
                  - if @landlord.errors[:postal_code].any?
                    %span.myerror
                      = @landlord.errors[:postal_code].first
                %br
                .field
                  %label Country
                  = f.text_field :country, :class => 'form-control'
                  - if @landlord.errors[:country].any?
                    %span.myerror
                      = @landlord.errors[:country].first
                %br
                .field
                  %label Occupation
                  %br
                  = f.select :occupation, options_for_select([["Select Occupation", ""], "Student", "Professional", "Other"]), {}, :class => 'form-control'
                  - if @landlord.errors[:occupation].any?
                    %span.myerror
                      = @landlord.errors[:occupation].first
                %br
                .field
                  %label Brief Description
                  = f.text_area :brief_description, :class => 'form-control'
                / %br
                / .actions
                /   = f.submit 'Submit', :class => 'btn btn-primary'
                /   = link_to 'Back', admin_landlords_path, :class => 'btn btn-primary'
                %br
                .box-footer
                  = f.submit 'Submit', :class => 'btn btn-primary' 
                  = link_to 'Back', admin_landlords_path, :class => 'btn btn-primary'
:javascript
  var imageLoader = document.getElementById('filePhoto');
      imageLoader.addEventListener('change', handleImage, false);
  function handleImage(e) {
      var reader = new FileReader();
      reader.onload = function (event) {
          $('#imgPreview').attr('src',event.target.result);
      }
      reader.readAsDataURL(e.target.files[0]);
  }

app/views/admin/landlords/edit.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      &nbsp;
      Edit Landlord
  = render 'form'

app/views/admin/landlords/index.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      &nbsp;
      List of Landlord
  = render 'fetchAllLandlord'

app/views/admin/landlords/new.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      &nbsp;
      Add New Landlord
  = render 'form'

app/views/admin/landlords/show.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1 Landlords Details
    .row
      .col-md-12
        .box.box-primary
          .box-body
            %table.table.table-striped
              %p#notice= notice
              %p
                %strong Landlord Id:
                = @landlord.id
              %p
                %strong Title:
                = @landlord.title
              %p
                %strong Full Name:
                = @landlord.full_name
              %p
                %strong Gender:
                = @landlord.gender
              %p
                %strong Date of Birth:
                = @landlord.date_of_birth
              %p
                %strong Address Type:
                = @landlord.address_type
              %p
                %strong Address:
                = @landlord.address
              %p
                %strong City:
                = @landlord.city
              %p
                %strong Postal Code:
                = @landlord.postal_code
              %p
                %strong Occupation:
                = @landlord.occupation
              %p
                %strong Description:
                = @landlord.brief_description
              %p
                %strong User Id:
                = @landlord.user_id
              %p
                %strong Account Type:
                = @landlord.user.account_type
              %p
                %strong User Name:
                = @landlord.user.username
              %p
                %strong Email:
                = @landlord.user.email
              - if @landlord.user.avatar.present?
                %p
                  %strong Photo:
                  = image_tag @landlord.user.avatar, :size => "50x50"
              %p
              .box-footer
                = link_to 'Edit', edit_admin_landlord_path(@landlord), :class => 'btn btn-primary'
                &nbsp;
                = link_to 'Back', admin_landlords_path, :class => 'btn btn-primary'
              