config/routes.rb
require 'api_constraints'

YourNextRoom::Application.routes.draw do
  devise_for :admins, controllers: { sessions: "admin/sessions" }
	namespace :admin do
		root 'home#index'
		resources :tenants
		resources :landlords
		resources :managers
		resources :users
    resources :admin_users
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :api do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      devise_scope :user do
        match '/sessions' => 'sessions#create', :via => :post
        match '/sessions' => 'sessions#destroy', :via => :delete

        match '/confirmations' => 'confirmations#create', :via => :post
        match '/confirmations' => 'confirmations#show', :via => :get

        match '/passwords' => 'passwords#create', :via => :post
        match '/passwords' => 'passwords#update', :via => :put

        match '/update_password' => 'passwords#update_password', :via => :put

      end
      resources :users, only: [:create]
      match '/users' => 'users#show', :via => :get
      match '/users' => 'users#update', :via => :put
      match '/users' => 'users#destroy', :via => :delete

      resources :tenants
      match '/tenants' => 'tenants#update', :via => :put
      match '/tenants' => 'tenants#destroy', :via => :delete

      resources :landlords
      match '/landlords' => 'landlords#update', :via => :put
      match '/landlords' => 'landlords#destroy', :via => :delete

      resources :managers
      match '/managers' => 'managers#update', :via => :put
      match '/managers' => 'managers#destroy', :via => :delete
    end
  end
end

app/views/layouts/_admin_content.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      &nbsp;
      Dashboard
    %section.content-header
      .row
        .col-md-4.col-sm-6.col-xs-12
          .info-box
            %span.info-box-icon.bg-red
              %i.ion.ion-ios-people-outline
            .info-box-content
              %span.info-box-text Tenants
              %span.info-box-number 
                = @total_tenants_count
            / /.info-box-content
          / /.info-box
        / /.col
        / fix for small devices only
        .clearfix.visible-sm-block
        .col-md-4.col-sm-6.col-xs-12
          .info-box
            %span.info-box-icon.bg-yellow
              %i.ion.ion-ios-people-outline
            .info-box-content
              %span.info-box-text Landlords
              %span.info-box-number 
                = @total_landlords_count
            / /.info-box-content
          / /.info-box
        / /.col
        .col-md-4.col-sm-6.col-xs-12
          .info-box
            %span.info-box-icon.bg-green
              %i.ion.ion-ios-people-outline
            .info-box-content
              %span.info-box-text Business Landlords
              %span.info-box-number 
                = @total_managers_count
            / /.info-box-content
          / /.info-box
        / /.col
      / /.row

app/views/layouts/_admin_footer.html.haml
%footer.main-footer
  %strong
    Copyright &copy; 2015
  All rights reserved.

app/views/layouts/_admin_header.html.haml
%header.main-header
  %a.logo{:href => "/admin"}
    / LOGO
    YourNextRoom 
  / Header Navbar: style can be found in header.less
  %nav.navbar.navbar-static-top{:role => "navigation"}   
    / Navbar Right Menu
    .navbar-custom-menu
      %ul.nav.navbar-nav
        / User Account: style can be found in dropdown.less
        %li.dropdown.user.user-menu
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            - if admin_signed_in?
              %img.user-image{:alt => "Admin User", :src => "/assets/user6-128x128.jpg"}
            - else
              %img.user-image{:alt => "Default User", :src => "/assets/user-big-icon.png"}
            - if admin_signed_in?
              %span.hidden-xs #{current_admin.email}
            - else
              %span.hidden-xs Default User
          %ul.dropdown-menu
            / User image
            %li.user-header
              - if admin_signed_in?
                %img.img-circle{:alt => "Admin User", :src => "/assets/user6-128x128.jpg"}/
              - else
                %img.img-circle{:alt => "Default User", :src => "/assets/user-big-icon.png"}/
              %p
              - if admin_signed_in?
                %p
                  %span.hidden-xs #{current_admin.email}
                %p
                  %small Member since #{current_admin.created_at}
              - else
                %p
                  %span.hidden-xs Default User
                %p
                  %small Member since Nov. 2012
            / Menu Footer
            %li.user-footer
              .pull-left
                %a.btn.btn-default.btn-flat{:href => "#"} Profile
              .pull-right
                = link_to "Sign out", destroy_admin_session_path, :method => :delete, :class => "btn btn-default"
                

app/views/layouts/_admin_sidebar.html.haml
/ Left side column. contains the logo and sidebar
%aside.main-sidebar
  / sidebar: style can be found in sidebar.less
  %section.sidebar
    / Sidebar user panel
    .user-panel
      .pull-left.image
        - if admin_signed_in?
          %img.img-circle{:alt => "Admin User", :src => "/assets/user6-128x128.jpg"}
        - else
          %img.img-circle{:alt => "Default User", :src => "/assets/user-big-icon.png"}
      .pull-left.info 
        - if admin_signed_in?
          %p Admin User
        - else
          %p Default User
    / sidebar menu: : style can be found in sidebar.less
    %ul.sidebar-menu
      %li.active.treeview
        %li.header USERS
        %li
          = link_to "Admin Users", admin_admin_users_path          
        %li
          = link_to "Tenants", admin_tenants_path 
        %li
          = link_to "Landlords", admin_landlords_path 
        %li
          = link_to "Business Landlords", admin_managers_path 
  / /.sidebar

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:charset => "UTF-8"}
      %title YNR ADMIN DASHBOARD
      %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}
        = stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track' => true
        = javascript_include_tag 'admin', 'data-turbolinks-track' => true
        = csrf_meta_tags
        / Font Awesome Icons
        %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}/
        / Ionicons
        %link{:href => "http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css", :rel => "stylesheet", :type => "text/css"}/
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  %body.skin-blue
    = render "layouts/admin_header"
    = render "layouts/admin_sidebar"
    = yield
    = render "layouts/admin_footer"
  / ./wrapper

app/views/layouts/admindevise.html.haml
!!!
%html
  %head
    %meta{:charset => "UTF-8"}
      %title YNR ADMIN DASHBOARD
      %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}
        = stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track' => true
        = javascript_include_tag 'admin', 'data-turbolinks-track' => true
        = csrf_meta_tags
        / Font Awesome Icons
        %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}/
        / Ionicons
        %link{:href => "http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css", :rel => "stylesheet", :type => "text/css"}/
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  %body.login-page
    = yield
  / ./wrapper

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title YourNextRoom
    = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/yournextroom.html.haml
!!!
%html{"ng-app" => "YourNextRoom"}
  %head
    %title Welcome to YNR::
    = stylesheet_link_tag 'application', media: 'all'
    %script{:src => "http://apis.google.com/js/client.js"}
    %script{:src => "http://apis.google.com/js/api.js"}
    %script{:src => "https://maps.googleapis.com/maps/api/js?libraries=places"}
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
  %body
    #wrap{"ng-view" => ""}
    = javascript_include_tag 'application'